# .github/dependabot.yml
version: 2
updates:
  # Maintain dependencies for pnpm
  - package-ecosystem: "npm" # Refers to npm ecosystem, pnpm uses this for lookup
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "main" # Or your development branch
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "dependabot"
    reviewers:
      - "robertocunha" # Replace with actual GitHub username(s) if desired
    ignore:
      # Example: ignore updates for a specific package
      # - dependency-name: "example-package"
      #   versions: ["2.x", "3.x"]
      # Example: ignore patch updates for all dependencies
      # - dependency-name: "*"
      #   update-types: ["version-update:semver-patch"]
      - dependency-name: "prisma" # Often updated, pin major/minor versions manually
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "github_actions"
      - "dependabot"
    reviewers:
      - "robertocunha" # Replace