/**
 * tRPC Router for Protocol Management
 */
import { TRPCError } from "@trpc/server";
// import { z as _z } from "zod"; // Marked as unused
import {
  router,
  publicProcedure,
  protectedProcedure,
  createCallerFactory,
} from "../trpc";
import {
  CreateProtocolInputSchema,
  ListProtocolsInputSchema,
  ProtocolIdInputSchema,
  UpdateProtocolVersionInputSchema,
} from "@/lib/validators/protocol-schema";
import type { ProtocolFullContent, FlowchartData } from "@/types/protocol";
import { ProtocolStatus, UserRole } from "@prisma/client";
import { Permission } from "@/lib/auth/permissions";
import { checkPermission } from "@/lib/auth/rbac";
import { logAuditEvent, AuditActions } from "@/lib/audit";

const DEFAULT_EMPTY_CONTENT: ProtocolFullContent = Object.fromEntries(
  Array.from({ length: 13 }, (_, i) => [
    (i + 1).toString(),
    {
      sectionNumber: i + 1,
      title: `Seção ${i + 1}`,
      content: "",
    },
  ]),
);

const DEFAULT_EMPTY_FLOWCHART: FlowchartData = {
  nodes: [],
  edges: [],
};

export const protocolRouter = router({
  create: protectedProcedure
    .input(CreateProtocolInputSchema)
    .mutation(async ({ ctx, input }) => {
      const { title, condition } = input;
      const userId = ctx.session.user.id;

      if (
        !checkPermission(
          ctx.session.user.role as UserRole,
          Permission.CREATE_PROTOCOL,
        )
      ) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Você não tem permissão para criar protocolos.",
        });
      }

      const codePrefix = condition.substring(0, 5).toUpperCase();
      const count = await ctx.db.protocol.count({
        where: { code: { startsWith: codePrefix } },
      });
      const protocolCode = `${codePrefix}-${(count + 1)
        .toString()
        .padStart(3, "0")}`;

      const protocol = await ctx.db.protocol.create({
        data: {
          // id will be generated by @default(cuid()) in schema
          title,
          condition,
          code: protocolCode,
          createdById: userId,
          status: ProtocolStatus.DRAFT,
          // updatedAt will be handled by @updatedAt in schema
          ProtocolVersion: {
            create: [
              {
                // id will be generated by @default(cuid()) in schema
                versionNumber: 1,
                createdById: userId,
                content: DEFAULT_EMPTY_CONTENT as any,
                flowchart: DEFAULT_EMPTY_FLOWCHART as any,
                changelogNotes: "Versão inicial criada.",
              },
            ],
          },
        },
        include: {
          ProtocolVersion: true,
        },
      });

      await logAuditEvent(ctx.db, {
        userId: userId,
        action: AuditActions.PROTOCOL_CREATE,
        resourceType: "Protocol",
        resourceId: protocol.id,
        details: {
          title: protocol.title,
          code: protocol.code,
          initialVersionId: protocol.ProtocolVersion[0]?.id,
        },
      });

      return protocol;
    }),

  list: publicProcedure
    .input(ListProtocolsInputSchema)
    .query(async ({ ctx, input }) => {
      const {
        page = 1,
        limit = 20,
        status,
        search,
        sortBy = "updatedAt",
        sortOrder = "desc",
      } = input;

      const whereClause: any = {};
      if (status) {
        whereClause.status = status;
      }
      if (search) {
        whereClause.OR = [
          { title: { contains: search, mode: "insensitive" } },
          { condition: { contains: search, mode: "insensitive" } },
          { code: { contains: search, mode: "insensitive" } },
        ];
      }

      const protocols = await ctx.db.protocol.findMany({
        where: whereClause,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: {
          [sortBy]: sortOrder,
        },
        include: {
          User: {
            select: { id: true, name: true, email: true },
          },
          _count: {
            select: { ProtocolVersion: true },
          },
          ProtocolVersion: {
            orderBy: { versionNumber: "desc" },
            take: 1,
            select: { versionNumber: true, createdAt: true },
          },
        },
      });

      const totalProtocols = await ctx.db.protocol.count({
        where: whereClause,
      });

      return {
        items: protocols,
        totalItems: totalProtocols,
        totalPages: Math.ceil(totalProtocols / limit),
        currentPage: page,
      };
    }),

  getById: protectedProcedure
    .input(ProtocolIdInputSchema)
    .query(async ({ ctx, input }) => {
      const protocol = await ctx.db.protocol.findUnique({
        where: { id: input.protocolId },
        include: {
          User: {
            select: { id: true, name: true, email: true },
          },
          ProtocolVersion: {
            orderBy: { versionNumber: "desc" },
            include: {
              User: {
                select: { id: true, name: true, email: true },
              },
            },
          },
        },
      });

      if (!protocol) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: `Protocolo com ID '${input.protocolId}' não encontrado.`,
        });
      }
      return protocol;
    }),

  update: protectedProcedure
    .input(UpdateProtocolVersionInputSchema)
    .mutation(async ({ ctx, input }) => {
      const { protocolId, content, flowchart, changelogNotes } = input;
      const userId = ctx.session.user.id;

      const protocol = await ctx.db.protocol.findUnique({
        where: { id: protocolId },
        include: {
          ProtocolVersion: { orderBy: { versionNumber: "desc" }, take: 1 },
        },
      });

      if (!protocol) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: `Protocolo com ID '${protocolId}' não encontrado.`,
        });
      }

      const canEditOwn = checkPermission(
        ctx.session.user.role as UserRole,
        Permission.EDIT_OWN_PROTOCOL,
        protocol.createdById,
        userId,
      );
      const canEditAny = checkPermission(
        ctx.session.user.role as UserRole,
        Permission.EDIT_ANY_PROTOCOL,
      );

      if (!canEditOwn && !canEditAny) {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "Você não tem permissão para editar este protocolo.",
        });
      }

      const latestVersionNumber =
        protocol.ProtocolVersion[0]?.versionNumber ?? 0;

      const newProtocolVersion = await ctx.db.protocolVersion.create({
        data: {
          // id will be generated by @default(cuid()) in schema
          protocolId: protocolId,
          versionNumber: latestVersionNumber + 1,
          content: (content ??
            protocol.ProtocolVersion[0]?.content ??
            DEFAULT_EMPTY_CONTENT) as any,
          flowchart: (flowchart ??
            protocol.ProtocolVersion[0]?.flowchart ??
            DEFAULT_EMPTY_FLOWCHART) as any,
          changelogNotes:
            changelogNotes ??
            `Atualização para versão ${latestVersionNumber + 1}.`,
          createdById: userId,
        },
      });

      await ctx.db.protocol.update({
        where: { id: protocolId },
        data: { updatedAt: new Date() }, // Prisma @updatedAt will handle this
      });

      await logAuditEvent(ctx.db, {
        userId: userId,
        action: AuditActions.PROTOCOL_VERSION_CREATE,
        resourceType: "ProtocolVersion",
        resourceId: newProtocolVersion.id,
        details: {
          protocolId: protocol.id,
          protocolCode: protocol.code,
          newVersionNumber: newProtocolVersion.versionNumber,
          changelog: newProtocolVersion.changelogNotes,
        },
      });

      return newProtocolVersion;
    }),
});

export const protocolCaller = createCallerFactory(protocolRouter);
